service: my-telegram-bot

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: eu-central-1
  environment:
    TELEGRAM_TOKEN: ${env:TELEGRAM_TOKEN}

package:
  exclude:
    - .git/**
    - .travis.yml
    - tox.ini
    - .tox/**
    - requirements.txt
    - .gitignore
    - README.rst

functions:
  post:
    handler: bot.webcomic_bot
    events:
      - http:
          path: my-custom-url
          method: post
          cors: true
